server.port=8077
allowed_origin=*
metrics.enabled=true

recaptcha.publickey=6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
recaptcha.secretkey=6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe

trace-api.base-url=https://api.staging.traceyour.events/v2
trace-api.api-key=no-key
breg.base-url=https://api.visitscotland.com/fake/submit/breg


notification.email.subject=Carbon Calculator Error Report (Broken Configuration)
notification.email.recipients=Jose.Calcines+ccg@visitscotland.com,Corina.Baillie@visitscotland.com





